### ISSUE TITLE
Releases with git-tags

### ISSUE THREAD

**Issue by tom-schoener** [subshell/o-neko#17]
We currently do not have a process to create versioned releases. Releases should follow [semantic versioning](https://semver.org/) with git-tags. 

All docker images should be pushed to https://hub.docker.com/r/subshellgmbh/o-neko

**Comment by tom-schoener** [comment]
I've created a release script in `release/release.sh` which sets the version for `package.json`, `pom.xml` and the git tag. The script checks if the version parameter is valid and if the git working directory is clean. 

Usage:
```sh
release/release.sh [<v[major.minor.path]> | major | minor | patch]

# Examples:
# Sets a specific version
release/release.sh v0.0.0

# patch
release/release.sh patch

# major
release/release.sh major
```
To deploy the changes, run `git push --tags origin master`. 

I would prefer CircleCI to execute the release script, but CircleCi does not provide a way to manually trigger jobs. They also do not support filtering of jobs by their commit message. There are workarounds (https://ideas.circleci.com/ideas/CCI-I-581?utm_medium=SEM&utm_source=gnb&utm_campaign=SEM-gb-DSA-Eng-ni&utm_content=&utm_term=dynamicSearch-&gclid=CjwKCAjwmKLzBRBeEiwACCVihltw44s2uJA5VNnyOaNHuaz6AZp4zkHnecXpApX6HQyVULG5bU0VBBoC2voQAvD_BwE) but I did not look further into them.

**Comment by tom-schoener** [comment]
I've added Windows support. The release script will be executed with Docker. The image is created locally with `docker build ./release -t oneko-release`. Creating a release is pretty easy:
```
docker run -it -v ${PWD}:/workspace oneko-release [<v[major.minor.patch]> | major | minor | patch]
git push --tags origin master
```
On windows, use `%cd%` or the absolute project path instead of `${PWD}`.

**Comment by philmtd** [comment]
#19 is merged now.
