### ISSUE TITLE
SelectVariables should select the current value when in the editing view

### ISSUE THREAD

**Issue by philmtd** [subshell/o-neko#7]
When a select variable has a value it should show as selected in the editing view. Currently the select-value shows as empty. The values are correctly visible on the dashboard.

**Buggy edit view:**
<img width="938" alt="edit-view-bug" src="https://user-images.githubusercontent.com/5818072/69146743-c30b6280-0ad0-11ea-8434-b49117477903.png">

**Correct dashboard view:**
<img width="624" alt="dashboard-ok" src="https://user-images.githubusercontent.com/5818072/69146745-c30b6280-0ad0-11ea-9ea4-6363d474a91c.png">

Edit: Apparently sometimes it works, though whether it works depends on the version. I could not find obvious similarities between the working or broken versions though.

**Comment by schwerlaut** [comment]
Approved and Merged your PR.

**Comment by philmtd** [comment]
You accidentally closed the wrong issue. Let me re-open it.

**Comment by philmtd** [comment]
You accidentally closed the wrong issue. Let me re-open it.
